version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: streaming-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  streamingapp:
    build: .
    container_name: streaming-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      # üß© Configuraci√≥n de conexi√≥n a MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/pstreaming
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # ‚öôÔ∏è Variables de Twilio (coloca tus valores reales)
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_PHONE: ${TWILIO_FROM_PHONE}

volumes:
  mysql_data: